//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class activityreport_config
    {
        public int id { get; set; }
        public int regionid { get; set; }
        public int territoryid { get; set; }
        public int teamid { get; set; }
        public int districtid { get; set; }
        public int cardid { get; set; }
        public int dashboardid { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> lastcompleted { get; set; }
        public int languageid { get; set; }
        public string timezoneid { get; set; }
        public int uid { get; set; }
    }
}
