//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public answer()
        {
            this.answerstrings = new HashSet<answerstring>();
        }
    
        public int id { get; set; }
        public int questionid { get; set; }
        public int sequence { get; set; }
        public string answer1 { get; set; }
        public string code { get; set; }
        public byte task { get; set; }
        public int taskquestionid { get; set; }
        public int taskuserid { get; set; }
        public int typeid { get; set; }
        public string taskemail { get; set; }
        public int linkid { get; set; }
        public int calendardays { get; set; }
        public int calendartime { get; set; }
        public string color { get; set; }
        public int categoryid { get; set; }
        public int alertid { get; set; }
        public int groupid { get; set; }
        public decimal answervalue { get; set; }
        public bool taskemailself { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answerstring> answerstrings { get; set; }
    }
}
