//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_byid
    {
        public int id { get; set; }
        public string tablename { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public int uniqueid { get; set; }
        public string columnname { get; set; }
        public string oldvalue { get; set; }
        public string newvalue { get; set; }
    }
}
