//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_association
    {
        public int id { get; set; }
        public string tablename { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public int uniqueid1 { get; set; }
        public int uniqueid2 { get; set; }
        public string uniquename { get; set; }
        public bool inserted { get; set; }
    }
}
