//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients_phone
    {
        public int clientid { get; set; }
        public int phoneid { get; set; }
        public int relationshipid { get; set; }
    
        public virtual client client { get; set; }
        public virtual phone phone { get; set; }
        public virtual clients_phone_relationship clients_phone_relationship { get; set; }
    }
}
