//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class imfinzidevEntities : DbContext
    {
        public imfinzidevEntities()
            : base("name=imfinzidevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountcategory> accountcategories { get; set; }
        public virtual DbSet<accountnumberrule> accountnumberrules { get; set; }
        public virtual DbSet<accounttype> accounttypes { get; set; }
        public virtual DbSet<AccountTypes_cards> AccountTypes_cards { get; set; }
        public virtual DbSet<activityreport_config> activityreport_config { get; set; }
        public virtual DbSet<activityreport_config_log> activityreport_config_log { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<answer> answers { get; set; }
        public virtual DbSet<answerstring> answerstrings { get; set; }
        public virtual DbSet<audit_association> audit_association { get; set; }
        public virtual DbSet<audit_byid> audit_byid { get; set; }
        public virtual DbSet<audit_byidname> audit_byidname { get; set; }
        public virtual DbSet<caColumnAccess> caColumnAccesses { get; set; }
        public virtual DbSet<caColumnAccess_messageQuestions> caColumnAccess_messageQuestions { get; set; }
        public virtual DbSet<caColumnAccess_questions> caColumnAccess_questions { get; set; }
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<client_documents> client_documents { get; set; }
        public virtual DbSet<client_tasks> client_tasks { get; set; }
        public virtual DbSet<clientcontacts_report_config> clientcontacts_report_config { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<clients_address> clients_address { get; set; }
        public virtual DbSet<clients_address_relationship> clients_address_relationship { get; set; }
        public virtual DbSet<clients_address_text> clients_address_text { get; set; }
        public virtual DbSet<clients_contact> clients_contact { get; set; }
        public virtual DbSet<clients_contact_relationship> clients_contact_relationship { get; set; }
        public virtual DbSet<clients_contact_text> clients_contact_text { get; set; }
        public virtual DbSet<clients_default_customfield> clients_default_customfield { get; set; }
        public virtual DbSet<clients_phone> clients_phone { get; set; }
        public virtual DbSet<clients_phone_relationship> clients_phone_relationship { get; set; }
        public virtual DbSet<clients_phone_text> clients_phone_text { get; set; }
        public virtual DbSet<clients_renumber> clients_renumber { get; set; }
        public virtual DbSet<clientsalert> clientsalerts { get; set; }
        public virtual DbSet<clientsfah> clientsfahs { get; set; }
        public virtual DbSet<clientsnote> clientsnotes { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<contact_address> contact_address { get; set; }
        public virtual DbSet<contact_address_relationship> contact_address_relationship { get; set; }
        public virtual DbSet<contact_address_text> contact_address_text { get; set; }
        public virtual DbSet<contact_customfield> contact_customfield { get; set; }
        public virtual DbSet<contact_phone> contact_phone { get; set; }
        public virtual DbSet<contact_phone_relationship> contact_phone_relationship { get; set; }
        public virtual DbSet<contact_phone_text> contact_phone_text { get; set; }
        public virtual DbSet<customfield> customfields { get; set; }
        public virtual DbSet<dashboard> dashboards { get; set; }
        public virtual DbSet<dashboard_statfilter> dashboard_statfilter { get; set; }
        public virtual DbSet<dashboard_statheading> dashboard_statheading { get; set; }
        public virtual DbSet<dashboard_statistic> dashboard_statistic { get; set; }
        public virtual DbSet<dashboardcount> dashboardcounts { get; set; }
        public virtual DbSet<dashboardline> dashboardlines { get; set; }
        public virtual DbSet<dashboardline_condition> dashboardline_condition { get; set; }
        public virtual DbSet<dashboardline_filter> dashboardline_filter { get; set; }
        public virtual DbSet<dashboardstring> dashboardstrings { get; set; }
        public virtual DbSet<dashboardtotal> dashboardtotals { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<gateway> gateways { get; set; }
        public virtual DbSet<group_messages> group_messages { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<help> helps { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<holidaygroup> holidaygroups { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<link> links { get; set; }
        public virtual DbSet<messageboard> messageboards { get; set; }
        public virtual DbSet<mobileo> mobileos { get; set; }
        public virtual DbSet<msgin> msgins { get; set; }
        public virtual DbSet<msgin_log> msgin_log { get; set; }
        public virtual DbSet<msgin_rejected> msgin_rejected { get; set; }
        public virtual DbSet<msgout> msgouts { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<phone> phones { get; set; }
        public virtual DbSet<prospect> prospects { get; set; }
        public virtual DbSet<prospects_import_header> prospects_import_header { get; set; }
        public virtual DbSet<prospects_status> prospects_status { get; set; }
        public virtual DbSet<prospectsnote> prospectsnotes { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<questionstring> questionstrings { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<report_column> report_column { get; set; }
        public virtual DbSet<report_columnsource> report_columnsource { get; set; }
        public virtual DbSet<report_columnstring> report_columnstring { get; set; }
        public virtual DbSet<reportstring> reportstrings { get; set; }
        public virtual DbSet<savedReportConfig> savedReportConfigs { get; set; }
        public virtual DbSet<smtpout> smtpouts { get; set; }
        public virtual DbSet<target> targets { get; set; }
        public virtual DbSet<targetrange> targetranges { get; set; }
        public virtual DbSet<targetvalue> targetvalues { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<term> terms { get; set; }
        public virtual DbSet<termchar> termchars { get; set; }
        public virtual DbSet<territory> territories { get; set; }
        public virtual DbSet<timezone> timezones { get; set; }
        public virtual DbSet<tracking_data> tracking_data { get; set; }
        public virtual DbSet<tracking_history_data> tracking_history_data { get; set; }
        public virtual DbSet<tracking_history_time> tracking_history_time { get; set; }
        public virtual DbSet<tracking_time> tracking_time { get; set; }
        public virtual DbSet<user_documents> user_documents { get; set; }
        public virtual DbSet<userDevice> userDevices { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<users_daysoff> users_daysoff { get; set; }
        public virtual DbSet<users_exereg> users_exereg { get; set; }
        public virtual DbSet<users_login> users_login { get; set; }
        public virtual DbSet<users_setting> users_setting { get; set; }
        public virtual DbSet<users_status> users_status { get; set; }
        public virtual DbSet<usersexpens> usersexpenses { get; set; }
        public virtual DbSet<UsersMileage> UsersMileages { get; set; }
        public virtual DbSet<viewoption> viewoptions { get; set; }
        public virtual DbSet<visitreport_config> visitreport_config { get; set; }
        public virtual DbSet<visitreport_config_log> visitreport_config_log { get; set; }
        public virtual DbSet<visitreport_run> visitreport_run { get; set; }
        public virtual DbSet<mobileapp> mobileapps { get; set; }
        public virtual DbSet<prospects_import_detail> prospects_import_detail { get; set; }
        public virtual DbSet<ReferralAccount> ReferralAccounts { get; set; }
        public virtual DbSet<ReportScheduler> ReportSchedulers { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<trace> traces { get; set; }
        public virtual DbSet<tracking> trackings { get; set; }
        public virtual DbSet<tracking_history> tracking_history { get; set; }
        public virtual DbSet<userdashboard> userdashboards { get; set; }
        public virtual DbSet<webservice_inputlog> webservice_inputlog { get; set; }
    }
}
