//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.addresses = new HashSet<address>();
            this.client_documents = new HashSet<client_documents>();
            this.clients_address = new HashSet<clients_address>();
            this.clients_contact = new HashSet<clients_contact>();
            this.clients_phone = new HashSet<clients_phone>();
            this.contacts = new HashSet<contact>();
            this.phones = new HashSet<phone>();
        }
    
        public int id { get; set; }
        public int importid { get; set; }
        public string number { get; set; }
        public string clientname { get; set; }
        public int regionid { get; set; }
        public int districtid { get; set; }
        public int userid { get; set; }
        public string website { get; set; }
        public int typeid { get; set; }
        public int msgcnt { get; set; }
        public System.DateTime lastmsg { get; set; }
        public int alertid { get; set; }
        public System.DateTime alertassigned { get; set; }
        public int alertdays { get; set; }
        public decimal totalsales { get; set; }
        public Nullable<System.DateTime> totalsalesdate { get; set; }
        public decimal forecastamount { get; set; }
        public Nullable<System.DateTime> forecastdate { get; set; }
        public decimal valuelastyear { get; set; }
        public decimal valuecurrent { get; set; }
        public decimal valuecompetitive { get; set; }
        public string number2 { get; set; }
        public int categoryid { get; set; }
        public decimal previoussale { get; set; }
        public Nullable<System.DateTime> previoussaledate { get; set; }
        public decimal currentsale { get; set; }
        public Nullable<System.DateTime> currentsaledate { get; set; }
        public int groupid { get; set; }
        public int cardid { get; set; }
        public Nullable<int> primary_contactid { get; set; }
        public Nullable<int> primary_addressid { get; set; }
        public Nullable<int> primary_phoneid { get; set; }
        public int notetab_default_date_filter { get; set; }
        public int valuestab_default_date_filter { get; set; }
        public int calldatatab_default_date_filter { get; set; }
        public int activitycardtab_default_date_filter { get; set; }
        public string source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address> addresses { get; set; }
        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client_documents> client_documents { get; set; }
        public virtual contact contact { get; set; }
        public virtual phone phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clients_address> clients_address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clients_contact> clients_contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clients_phone> clients_phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact> contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phone> phones { get; set; }
    }
}
