//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientsnote
    {
        public int id { get; set; }
        public int clientid { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public int userid { get; set; }
        public string notes { get; set; }
        public bool iscomment { get; set; }
        public System.DateTime lastchanged { get; set; }
        public int msginid { get; set; }
        public int trackingdataid { get; set; }
    
        public virtual clientsnote clientsnotes1 { get; set; }
        public virtual clientsnote clientsnote1 { get; set; }
    }
}
