//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients_renumber
    {
        public int id { get; set; }
        public int clientid { get; set; }
        public System.DateTime renumberedat { get; set; }
        public string oldnumber { get; set; }
        public string newnumber { get; set; }
        public string status { get; set; }
    }
}
