//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_documents
    {
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string FileType { get; set; }
        public string ActualFileName { get; set; }
    
        public virtual client client { get; set; }
        public virtual user user { get; set; }
    }
}
