//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int id { get; set; }
        public string companyid { get; set; }
        public string companyname { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postal { get; set; }
        public string country { get; set; }
        public string contact1 { get; set; }
        public string contact2 { get; set; }
        public string contact3 { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string phone3 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string email3 { get; set; }
        public string dbname { get; set; }
        public string smtpserver { get; set; }
        public string smtpuser { get; set; }
        public string smtppassword { get; set; }
        public string smtpfrom { get; set; }
        public string rssfeed { get; set; }
        public string rssindustry { get; set; }
        public byte multiplecards { get; set; }
        public int hourstart { get; set; }
        public int hourend { get; set; }
        public int maxcolumns { get; set; }
        public int fanat { get; set; }
        public string googlemapkey { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public byte answertasks { get; set; }
        public byte forecastquestions { get; set; }
        public byte numericquestions { get; set; }
        public byte alphaquestions { get; set; }
        public byte mobileinterface { get; set; }
        public byte prospectsinterface { get; set; }
        public int addprospects { get; set; }
        public byte qadateselect { get; set; }
        public string shortcode { get; set; }
        public string webserver { get; set; }
        public byte faquotastatistics { get; set; }
        public byte faforecaststatistics { get; set; }
        public int dashboardtotals { get; set; }
        public int dashboardcounts { get; set; }
        public int calltimers { get; set; }
        public int defaultcardsource { get; set; }
        public int mastercard { get; set; }
        public string dbschedule { get; set; }
        public int monthly { get; set; }
        public byte rollups { get; set; }
        public byte limitcardsbydistrict { get; set; }
        public byte roclients { get; set; }
        public string ftppath { get; set; }
        public string displayname_expression { get; set; }
        public byte remoteaccess_clients { get; set; }
        public byte cardoverride { get; set; }
        public string cardsbyname { get; set; }
        public int allClients { get; set; }
        public int logintimeout { get; set; }
        public int clientautoassign { get; set; }
        public int allowfabackout { get; set; }
        public byte contactstyle { get; set; }
        public int uifollowsdefaultcard { get; set; }
        public int defaultUserPermissionID { get; set; }
        public int showhistory { get; set; }
        public int daterangefilter { get; set; }
        public int disableclientnumber { get; set; }
        public int subdomain { get; set; }
        public int disableclientalert { get; set; }
        public int disableclientcategory { get; set; }
        public int disableclientnumber2 { get; set; }
        public int reportdocuments { get; set; }
        public int hide_optional_answers_for_mobileapp { get; set; }
        public int hide_client_task { get; set; }
        public int autogenaratedclientnumber { get; set; }
        public int enable_email_notification { get; set; }
        public string newClientNotificationEmail { get; set; }
        public int parentchildclients { get; set; }
        public int clientsmerge { get; set; }
        public int allowwebapi { get; set; }
        public string apikey { get; set; }
        public string api_calling_ip { get; set; }
        public int submitactivitiestoexternalwebservice { get; set; }
    }
}
