//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_address_text
    {
        public int relationshipid { get; set; }
        public int languageid { get; set; }
        public string text { get; set; }
    
        public virtual contact_address_relationship contact_address_relationship { get; set; }
        public virtual language language { get; set; }
    }
}
