//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboardline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dashboardline()
        {
            this.dashboardline_condition = new HashSet<dashboardline_condition>();
        }
    
        public int id { get; set; }
        public int dashboardid { get; set; }
        public string name { get; set; }
        public int sequence { get; set; }
        public string format { get; set; }
        public string destination { get; set; }
        public bool computed { get; set; }
        public string table_name { get; set; }
        public string expression { get; set; }
        public string joins { get; set; }
    
        public virtual dashboard dashboard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dashboardline_condition> dashboardline_condition { get; set; }
    }
}
