//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday
    {
        public int id { get; set; }
        public int length { get; set; }
        public string name { get; set; }
        public int groupid { get; set; }
        public int month { get; set; }
        public int day { get; set; }
        public Nullable<int> week { get; set; }
    
        public virtual holidaygroup holidaygroup { get; set; }
    }
}
