//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class messageboard
    {
        public int id { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> districtid { get; set; }
        public Nullable<int> userlevel { get; set; }
        public string messagetext { get; set; }
    }
}
