//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class msgin
    {
        public int id { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public string mobilenumber { get; set; }
        public string message { get; set; }
        public string source { get; set; }
        public Nullable<System.DateTime> processed { get; set; }
        public string status { get; set; }
        public int cardid { get; set; }
        public int userid { get; set; }
        public int clientid { get; set; }
        public int teamid { get; set; }
        public int territoryid { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
    }
}
