//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class msgin_log
    {
        public int id { get; set; }
        public string oldvalue { get; set; }
        public string newvalue { get; set; }
        public string msgid { get; set; }
        public Nullable<System.DateTime> inserteddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
    }
}
