//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public permission()
        {
            this.users = new HashSet<user>();
            this.accounttypes = new HashSet<accounttype>();
            this.accountcategories = new HashSet<accountcategory>();
            this.clientsalerts = new HashSet<clientsalert>();
            this.districts = new HashSet<district>();
            this.groups = new HashSet<group>();
            this.regions = new HashSet<region>();
        }
    
        public int id { get; set; }
        public int isRole { get; set; }
        public string name { get; set; }
        public int allClients { get; set; }
        public int roClients { get; set; }
        public int contactsRead { get; set; }
        public int userLevel { get; set; }
        public bool editMessage { get; set; }
        public bool defaultToUserRegion { get; set; }
        public bool defaultToUserDistrict { get; set; }
        public bool hideActiveStatus { get; set; }
        public bool schedule_email { get; set; }
        public bool hideExportClient { get; set; }
        public bool allowCustomDetailEditing { get; set; }
        public bool field_agent_reassignment { get; set; }
        public bool Allow_Client_Region_district_change { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accounttype> accounttypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accountcategory> accountcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientsalert> clientsalerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<district> districts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<region> regions { get; set; }
    }
}
