//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospect
    {
        public int id { get; set; }
        public int importid { get; set; }
        public string number { get; set; }
        public string name { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> assigned { get; set; }
        public Nullable<System.DateTime> lastcontact { get; set; }
        public int statusid { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postal { get; set; }
        public string country { get; set; }
        public string contact1 { get; set; }
        public string title1 { get; set; }
        public string phone1 { get; set; }
        public string fax1 { get; set; }
        public string email1 { get; set; }
        public string contact2 { get; set; }
        public string title2 { get; set; }
        public string phone2 { get; set; }
        public string fax2 { get; set; }
        public string email2 { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
        public decimal valuelastyear { get; set; }
        public decimal valuecompetitive { get; set; }
        public string number2 { get; set; }
        public int categoryid { get; set; }
        public string cell1 { get; set; }
        public string cell2 { get; set; }
        public string contact3 { get; set; }
        public string title3 { get; set; }
        public string email3 { get; set; }
        public string phone3 { get; set; }
        public string fax3 { get; set; }
        public string cell3 { get; set; }
        public string contact4 { get; set; }
        public string title4 { get; set; }
        public string email4 { get; set; }
        public string phone4 { get; set; }
        public string fax4 { get; set; }
        public string cell4 { get; set; }
        public string contact5 { get; set; }
        public string title5 { get; set; }
        public string email5 { get; set; }
        public string phone5 { get; set; }
        public string fax5 { get; set; }
        public string cell5 { get; set; }
        public string comments { get; set; }
        public decimal valuecurrent { get; set; }
        public int cardid { get; set; }
    }
}
