//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospectsnote
    {
        public int id { get; set; }
        public int prospectid { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public int userid { get; set; }
        public string notes { get; set; }
    
        public virtual prospectsnote prospectsnotes1 { get; set; }
        public virtual prospectsnote prospectsnote1 { get; set; }
    }
}
