//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospects_import_header
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.DateTime uploadeddatetime { get; set; }
        public Nullable<System.DateTime> processeddatetime { get; set; }
        public string filename { get; set; }
        public string pathfilename { get; set; }
        public int startrow { get; set; }
        public int rows { get; set; }
        public int imported { get; set; }
        public int dupclients { get; set; }
        public int dupprospects { get; set; }
        public Nullable<System.DateTime> pdeleteddatetime { get; set; }
        public int pdeleteduserid { get; set; }
        public Nullable<System.DateTime> cdeleteddatetime { get; set; }
        public int cdeleteduserid { get; set; }
    }
}
