//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospects_import_detail
    {
        public int importid { get; set; }
        public string columnname { get; set; }
        public string excelcolumn { get; set; }
        public string defaultvalue { get; set; }
    }
}
