//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        public int id { get; set; }
        public string provider1 { get; set; }
        public string domain { get; set; }
        public string website { get; set; }
        public string country { get; set; }
        public int gatewayid { get; set; }
    }
}
