//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.caColumnAccess_messageQuestions = new HashSet<caColumnAccess_messageQuestions>();
            this.caColumnAccess_questions = new HashSet<caColumnAccess_questions>();
            this.questionstrings = new HashSet<questionstring>();
        }
    
        public int id { get; set; }
        public short sequence { get; set; }
        public string question1 { get; set; }
        public int cardid { get; set; }
        public int answertype { get; set; }
        public int dailycallstats { get; set; }
        public byte clientsale { get; set; }
        public int forecastdefault { get; set; }
        public byte forecastcumulative { get; set; }
        public byte forecastreset { get; set; }
        public int dashboardtotal { get; set; }
        public int dashboardcount { get; set; }
        public int linkid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caColumnAccess_messageQuestions> caColumnAccess_messageQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caColumnAccess_questions> caColumnAccess_questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<questionstring> questionstrings { get; set; }
    }
}
