//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_columnsource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public report_columnsource()
        {
            this.report_column = new HashSet<report_column>();
            this.report_columnstring = new HashSet<report_columnstring>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool computed { get; set; }
        public string table_name { get; set; }
        public string expression { get; set; }
        public string aggregate { get; set; }
        public string datatype { get; set; }
        public string joins { get; set; }
        public string conditions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_column> report_column { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_columnstring> report_columnstring { get; set; }
    }
}
