//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public report()
        {
            this.reportstrings = new HashSet<reportstring>();
            this.report_column = new HashSet<report_column>();
        }
    
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int basis { get; set; }
        public string limit_table { get; set; }
        public int limit_rows { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime last_modified { get; set; }
        public int cardid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportstring> reportstrings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_column> report_column { get; set; }
        public virtual user user { get; set; }
    }
}
