//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class savedReportConfig
    {
        public int id { get; set; }
        public int cardid { get; set; }
        public int languageid { get; set; }
        public int reportid { get; set; }
        public int timeSpan { get; set; }
        public int usertype { get; set; }
        public int uid { get; set; }
        public int userid { get; set; }
    }
}
