//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class targetvalue
    {
        public int targetid { get; set; }
        public int userid { get; set; }
        public int rangeid { get; set; }
        public decimal value { get; set; }
    
        public virtual target target { get; set; }
        public virtual targetrange targetrange { get; set; }
        public virtual user user { get; set; }
    }
}
