//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersexpens
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public decimal amount { get; set; }
        public string description { get; set; }
        public System.DateTime lastchanged { get; set; }
        public Nullable<int> clientid { get; set; }
        public string category { get; set; }
        public string merchant { get; set; }
        public Nullable<int> documentid { get; set; }
    
        public virtual user_documents user_documents { get; set; }
    }
}
