//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_login
    {
        public int id { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public int userid { get; set; }
        public string ipaddr { get; set; }
        public string browsername { get; set; }
        public string browsermajorversion { get; set; }
        public string browserminorversion { get; set; }
        public string platform { get; set; }
        public string osversion { get; set; }
    }
}
