//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int id { get; set; }
        public string notificationmsg { get; set; }
        public Nullable<bool> isviewed { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> createdatetimeutc { get; set; }
        public Nullable<System.DateTime> modifydatetimeutc { get; set; }
        public int initiatoruserid { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
