//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_daysoff
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int enteredby { get; set; }
        public System.DateTime entereddate { get; set; }
        public System.DateTime scheduledoff { get; set; }
        public string comment { get; set; }
    }
}
