//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewoption
    {
        public int id { get; set; }
        public bool dash_Number_Field { get; set; }
        public bool dash_Contract_Field { get; set; }
        public bool dash_Name_Field { get; set; }
        public bool dash_Message_Field { get; set; }
        public bool dash_Type_Field { get; set; }
        public bool dash_Category_Field { get; set; }
        public bool dash_Flag_Field { get; set; }
        public bool dash_Region_Field { get; set; }
        public bool dash_FAgent_Field { get; set; }
        public bool dash_District_Field { get; set; }
        public bool dash_Group_Field { get; set; }
        public bool dash_Card_Field { get; set; }
        public bool dash_MarketValue_Field { get; set; }
        public bool dash_PrevSale_Field { get; set; }
        public bool dash_CurrSale_Field { get; set; }
        public bool dash_ValueLastYr_Field { get; set; }
        public bool dash_TotalSales_Field { get; set; }
        public bool dash_ForcastAmt_Field { get; set; }
        public bool dash_Count_Column { get; set; }
        public bool dash_Number_Column { get; set; }
        public bool dash_Name_Column { get; set; }
        public bool dash_Card_Column { get; set; }
        public bool dash_Type_Column { get; set; }
        public bool dash_Category_Column { get; set; }
        public bool dash_FAgent_Column { get; set; }
        public bool dash_LastYear_Column { get; set; }
        public bool dash_Competitive_Column { get; set; }
        public bool field_Number_Field { get; set; }
        public bool field_Contract_Field { get; set; }
        public bool field_Name_Field { get; set; }
        public bool field_Message_Field { get; set; }
        public bool field_Type_Field { get; set; }
        public bool field_Category_Field { get; set; }
        public bool field_Card_Field { get; set; }
        public bool field_Flag_Field { get; set; }
        public bool field_MarketValue_Field { get; set; }
        public bool field_ValueLastYr_Field { get; set; }
        public bool field_PrevSale_Field { get; set; }
        public bool field_TotalSales_Field { get; set; }
        public bool field_CurrSale_Field { get; set; }
        public bool field_ForcastAmt_Field { get; set; }
        public bool field_WebSite_Field { get; set; }
        public bool field_Count_Column { get; set; }
        public bool field_Number_Column { get; set; }
        public bool field_Contract_Column { get; set; }
        public bool field_Name_Column { get; set; }
        public bool field_FAgent_Column { get; set; }
        public bool field_Card_Column { get; set; }
        public bool field_Type_Column { get; set; }
        public bool field_Category_Column { get; set; }
        public bool field_Group_Column { get; set; }
        public bool field_Region_Column { get; set; }
        public bool field_District_Column { get; set; }
        public bool field_LastYear_Column { get; set; }
        public bool field_Competitive_Column { get; set; }
        public bool field_Contact_Column { get; set; }
    }
}
