//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitreport_config
    {
        public int id { get; set; }
        public int from { get; set; }
        public int to { get; set; }
        public int langid { get; set; }
        public string timezoneid { get; set; }
        public Nullable<System.DateTime> lastcompleted { get; set; }
    }
}
