//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitreport_run
    {
        public int id { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public Nullable<System.DateTime> rantime { get; set; }
        public string filenamemask { get; set; }
        public Nullable<int> configid { get; set; }
        public int languageid { get; set; }
        public string timezoneid { get; set; }
    }
}
