//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolisTech.FRSAdminPortal.Data.DbContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class webservice_inputlog
    {
        public string mobilenumber { get; set; }
        public string sessionid { get; set; }
        public System.DateTime datetimestamp { get; set; }
        public string data { get; set; }
    }
}
